# SPDX-License-Identifier: GPL-2.0+

udma-$(CONFIG_UB_UDMA) := udma_main.o udma_cmd.o udma_common.o udma_ctx.o udma_db.o \
	     udma_rct.o udma_tid.o udma_debugfs.o udma_eq.o udma_jfc.o \
	     udma_ctrlq_tp.o udma_eid.o udma_ctl.o

obj-m := udma.o
