# SPDX-License-Identifier: GPL-2.0+

obj-$(CONFIG_UB_UBUS) += ub-driver.o controller.o config.o

ubus-y := ubus_driver.o sysfs.o ubus_controller.o msg.o ubus_config.o port.o cc.o eid.o cna.o route.o
ubus-y += enum.o resource.o

obj-$(CONFIG_UB_UBUS_BUS) += ubus.o
