/* SPDX-License-Identifier: GPL-2.0+ WITH Linux-syscall-note */
/*
 * Copyright (c) HiSilicon Technologies Co., Ltd. 2025. All rights reserved.
 */

#ifndef _UAPI_UB_UBUS_UBUS_REGS_H_
#define _UAPI_UB_UBUS_UBUS_REGS_H_

enum ub_cfg_cap_id {
	UB_CFG0_BASIC_CAP = 0x000,
	UB_SHP_CAP = 0x002,
	UB_ERR_RECORD_CAP = 0x003,
	UB_ERR_INFO_CAP = 0x004,
	UB_EMQ_CAP = 0x005,
	UB_CFG1_BASIC_CAP = 0x100,
	UB_DECODER_CAP = 0x101,
	UB_JETTY_CAP = 0x102,
	UB_INT_TYPE1_CAP = 0x103,
	UB_INT_TYPE2_CAP = 0x104,
	UB_MEM_CAP = 0x106,
};

enum ub_port_cap_id {
	UB_PORT_CAP15_QDLWS = 15,
};

#define UB_SLICE_SZ 0x00000400
#define UB_CFG_BITMAP_SIZE 32
#define UB_ROUTE_TABLE_SZ 0x40000000
#define UB_CFG0_SUPPORT_FEATURE_SIZE 16
#define UB_GUID_SIZE 16
#define UB_EID_SIZE 16
#define UB_FM_EID_SIZE 16
#define UB_CFG1_SUPPORT_FEATURE_SIZE 16
#define UB_PORT_SLICE_START 0x00080000
#define UB_ROUTE_TABLE_SLICE_START 0x3c0000000
#define UB_CFG_SAPCE_SLICE_END 0x400000000
#define UB_ADDR_TO_POS(a) ((a) << 2)
#define UB_PORT_SLICE_SIZE UB_ADDR_TO_POS(0x10000)

/* CFG0 BASIC */
#define UB_CFG0_BASIC_SLICE 0x0 /* 0x0 */
#define UB_TOTAL_NUMBER_PORT 0x4 /* 0x1 */
#define UB_TOTAL_NUMBER_ENTITIES 0x6
#define UB_CFG0_CAP_BITMAP 0x8 /* 0x2 */
#define UB_FEATURE_SUPPORT_0 0x28 /* 0xA */
#define  UB_SW_SUPPORT BIT(7)
#define  UB_CC_SUPPORT BIT(9)
#define UB_GUID 0x38 /* 0xE */
#define UB_EID_0 0x48 /* 0x12 */
#define UB_EID_3 0x54 /* 0x15 */
#define UB_FM_EID_0 0x58 /* 0x16 */
#define UB_PRIMARY_CNA 0x68 /* 0x1A */
#define  UB_PRIMARY_CNA_MASK GENMASK(23, 0)
#define UB_UPI 0x7c /* 0x1f */
#define UB_MODULE 0x80 /* 0x20 */
#define  UB_MODULE_ID_MASK GENMASK(15, 0)
#define UB_ENTITY_RST 0x84 /* 0x21 */
#define  UB_ENTITY_RST_BIT 0x1
#define UB_MTU_CFG 0x8c /* 0x23 */
#define  UB_MTU_CFG_BITS 0x7
#define UB_CC_EN 0x90 /* 0x24 */
#define  UB_CC_EN_BIT 0x1
#define UB_TH_EN 0x94 /* 0x25 */
#define  UB_TH_EN_BIT 0x1
#define UB_FM_CNA 0x98 /* 0x26 */
#define  UB_FM_CNA_MASK GENMASK(23, 0)
#define UB_UEID_0 0x9c /* 0x27 */
#define UB_UEID_1 0xa0 /* 0x28 */
#define UB_UEID_2 0xa4 /* 0x29 */
#define UB_UEID_3 0xa8 /* 0x2A */
#define UB_UCNA 0xac /* 0x2B */
#define  UB_UCNA_MASK GENMASK(23, 0)

/* SHP CAP */
#define UB_SLOT_START UB_ADDR_TO_POS(0x200)
#define UB_SLOT_POS UB_ADDR_TO_POS(0x10)
#define UB_SLOT_NUM UB_ADDR_TO_POS(0x1)
#define UB_SLOT_CAP UB_ADDR_TO_POS(0x2)
#define  UB_SLOT_PPS 0x1
#define  UB_SLOT_WLPS 0x2
#define  UB_SLOT_PLPS 0x4
#define  UB_SLOT_PDSS 0x8
#define UB_SLOT_PORT UB_ADDR_TO_POS(0x3)
#define  UB_SLOT_START_PORT 0x0000ffff
#define UB_SLOT_PP_CTRL UB_ADDR_TO_POS(0x4)
#define  UB_SLOT_PP_CTRL_MASK BIT(0)
#define UB_SLOT_WL_CTRL UB_ADDR_TO_POS(0x5)
#define  UB_SLOT_WL_CTRL_MASK GENMASK(1, 0)
#define UB_SLOT_PL_CTRL UB_ADDR_TO_POS(0x6)
#define  UB_SLOT_PL_CTRL_MASK GENMASK(1, 0)
#define UB_SLOT_MS_CTRL UB_ADDR_TO_POS(0x7)
#define  UB_SLOT_MS_CTRL_MASK BIT(0)
#define UB_SLOT_PD_CTRL UB_ADDR_TO_POS(0x8)
#define  UB_SLOT_PD_CTRL_MASK BIT(0)
#define UB_SLOT_PDS_CTRL UB_ADDR_TO_POS(0x9)
#define  UB_SLOT_PDS_CTRL_MASK BIT(0)
#define UB_SLOT_PW_CTRL UB_ADDR_TO_POS(0xA)
#define UB_SLOT_PP_STA UB_ADDR_TO_POS(0xB)
#define  UB_SLOT_PP_STA_MASK BIT(0)
#define UB_SLOT_PD_STA UB_ADDR_TO_POS(0xC)
#define  UB_SLOT_PD_STA_MASK BIT(0)
#define UB_SLOT_PDSC_STA UB_ADDR_TO_POS(0xD)
#define  UB_SLOT_PDSC_STA_MASK BIT(0)

/* CFG1 BASIC */
#define UB_CFG1_BASIC 0x40000
#define UB_CFG1_BASIC_SLICE (0x0 + UB_CFG1_BASIC) /* 0x0 */
#define UB_CFG1_CAP_BITMAP (0x4 + UB_CFG1_BASIC) /* 0x1 */
#define  UB_DECODER_CAP_BIT 0x2
#define  UB_JETTY_CAP_BIT 0x4
#define  UB_INT_TYPE1_CAP_BIT 0x8
#define  UB_INT_TYPE2_CAP_BIT 0x10
#define  UB_MEM_CAP_BIT 0x40
#define UB_CFG1_SUPPORT_FEATURE_L (0x24 + UB_CFG1_BASIC) /* 0x9 */
#define  UB_VDBS_SUPPORT 0x1
#define  UB_VDSS_SUPPORT 0x2
#define  UB_MGS_SUPPORT 0x4
#define  UB_UBBAS_SUPPORT 0x20
#define  UB_ERS0S_SUPPORT 0x40
#define  UB_ERS1S_SUPPORT 0x80
#define  UB_ERS2S_SUPPORT 0x100
#define  UB_CDMAS_SUPPORT 0x200
#define  UB_DECODER_JURIS 0x400
#define UB_ERS0_SS (0x34 + UB_CFG1_BASIC) /* 0xD */
#define UB_ERS1_SS (0x38 + UB_CFG1_BASIC) /* 0xE */
#define UB_ERS2_SS (0x3c + UB_CFG1_BASIC) /* 0xF */
#define UB_ERS0_SA_L (0x40 + UB_CFG1_BASIC) /* 0x10 */
#define UB_ERS0_SA_H (0x44 + UB_CFG1_BASIC) /* 0x11 */
#define UB_ERS1_SA_L (0x48 + UB_CFG1_BASIC) /* 0x12 */
#define UB_ERS1_SA_H (0x4c + UB_CFG1_BASIC) /* 0x13 */
#define UB_ERS2_SA_L (0x50 + UB_CFG1_BASIC) /* 0x14 */
#define UB_ERS2_SA_H (0x54 + UB_CFG1_BASIC) /* 0x15 */
#define UB_ERS0_UBBA_L (0x58 + UB_CFG1_BASIC) /* 0x16 */
#define UB_ERS0_UBBA_H (0x5c + UB_CFG1_BASIC) /* 0x17 */
#define UB_ERS1_UBBA_L (0x60 + UB_CFG1_BASIC) /* 0x18 */
#define UB_ERS1_UBBA_H (0x64 + UB_CFG1_BASIC) /* 0x19 */
#define UB_ERS2_UBBA_L (0x68 + UB_CFG1_BASIC) /* 0x1A */
#define UB_ERS2_UBBA_H (0x6c + UB_CFG1_BASIC) /* 0x1B */
#define UB_ELR (0x70 + UB_CFG1_BASIC) /* 0x1C */
#define  UB_ELR_BIT 0x1
#define UB_ELR_DONE (0x74 + UB_CFG1_BASIC) /* 0x1D */
#define  UB_ELR_DONE_BIT 0x1
#define UB_SYS_PGS (0x84 + UB_CFG1_BASIC) /* 0x21 */
#define  UB_SYS_PGS_SIZE 0x1
#define UB_EU_TBA_L (0x88 + UB_CFG1_BASIC) /* 0x22 */
#define UB_EU_TBA_H (0x8c + UB_CFG1_BASIC) /* 0x23 */
#define UB_EU_TEN (0x90 + UB_CFG1_BASIC) /* 0x24 */
#define UB_CLASS_CODE (0xa4 + UB_CFG1_BASIC) /* 0x29 */
#define  UB_BASE_CODE_MASK GENMASK(7, 0)
#define  UB_SUB_CODE_MASK GENMASK(15, 8)
#define UB_ENTITY_TOKEN_ID (0xb4 + UB_CFG1_BASIC) /* 0x2D */
#define  UB_TOKEN_ID_MASK GENMASK(19, 0)
#define UB_BUS_ACCESS_EN (0xb8 + UB_CFG1_BASIC) /* 0x2E */
#define  UB_BUS_ACCESS_EN_BIT 0x1
#define UB_ENTITY_RS_ACCESS_EN (0xbc + UB_CFG1_BASIC) /* 0x2F */
#define  UB_ENTITY_RS_ACCESS_EN_BIT 0x1

/* DECODER CAP */
#define DECODER_CAP_START 0x00040400
#define DECODER_POS(pos) (DECODER_CAP_START + ((pos) << 2))
#define DECODER_CAP DECODER_POS(0x1)
#define DECODER_CTRL DECODER_POS(0x2)
#define DECODER_MATT_BA0 DECODER_POS(0x3)
#define DECODER_MATT_BA1 DECODER_POS(0x4)
#define DECODER_MMIO_BA0 DECODER_POS(0x5)
#define DECODER_MMIO_BA1 DECODER_POS(0x6)
#define DECODER_USI_IDX DECODER_POS(0x7)
#define DECODER_CMDQ_CFG DECODER_POS(0x10)
#define DECODER_CMDQ_PROD DECODER_POS(0x11)
#define DECODER_CMDQ_CONS DECODER_POS(0x12)
#define DECODER_CMDQ_BASE_ADDR0 DECODER_POS(0x13)
#define DECODER_CMDQ_BASE_ADDR1 DECODER_POS(0x14)
#define DECODER_EVENTQ_CFG DECODER_POS(0x20)
#define DECODER_EVENTQ_PROD DECODER_POS(0x21)
#define DECODER_EVENTQ_CONS DECODER_POS(0x22)
#define DECODER_EVENTQ_BASE_ADDR0 DECODER_POS(0x23)
#define DECODER_EVENTQ_BASE_ADDR1 DECODER_POS(0x24)

/* INT_TYPE1_CAP */
#define UB_CFG1_INT_TYPE1_CAP 0x40c00
#define UB_INT_TYPE1_ENABLE (0x4 + UB_CFG1_INT_TYPE1_CAP) /* 0x1 */
#define UB_INT_TYPE1_SUP_INT_NUM (0x8 + UB_CFG1_INT_TYPE1_CAP) /* 0x2 */
#define UB_INT_TYPE1_EN_INT_NUM (0xC + UB_CFG1_INT_TYPE1_CAP) /* 0x3 */
#define UB_INT_TYPE1_INT_DATA (0x10 + UB_CFG1_INT_TYPE1_CAP) /* 0x4 */
#define UB_INT_TYPE1_INT_ADDR_L (0x14 + UB_CFG1_INT_TYPE1_CAP) /* 0x5 */
#define UB_INT_TYPE1_INT_ADDR_H (0x18 + UB_CFG1_INT_TYPE1_CAP) /* 0x6 */
#define UB_INT_TYPE1_INT_ID (0x1c + UB_CFG1_INT_TYPE1_CAP) /* 0x7 */
#define UB_INT_TYPE1_INT_MASK (0x20 + UB_CFG1_INT_TYPE1_CAP) /* 0x8 */
#define UB_INT_TYPE1_INT_PENDING (0x24 + UB_CFG1_INT_TYPE1_CAP) /* 0x9 */

/* INT_TYPE2_CAP */
#define UB_CFG1_CAP_INT_CAP 0x41000
#define UB_INT_CAP_SLICE (0x0 + UB_CFG1_CAP_INT_CAP) /* 0x0 */
#define UB_INT_INFO (0x4 + UB_CFG1_CAP_INT_CAP) /* 0x1 */
#define  UB_NUM_OF_INTR_VECTOR_TBL (0x4 + UB_CFG1_CAP_INT_CAP)
#define  UB_NUM_OF_INTR_ADDR_TBL (0x6 + UB_CFG1_CAP_INT_CAP)
#define UB_INT_VECTOR_TBL_SA_L (0x8 + UB_CFG1_CAP_INT_CAP) /* 0x2 */
#define UB_INT_VECTOR_TBL_SA_H (0xc + UB_CFG1_CAP_INT_CAP) /* 0x3 */
#define UB_INT_ADDR_TBL_SA_L (0x10 + UB_CFG1_CAP_INT_CAP) /* 0x4 */
#define UB_INT_ADDR_TBL_SA_H (0x14 + UB_CFG1_CAP_INT_CAP) /* 0x5 */
#define UB_INT_PENDING_TBL_SA_L (0x18 + UB_CFG1_CAP_INT_CAP) /* 0x6 */
#define UB_INT_PENDING_TBL_SA_H (0x1c + UB_CFG1_CAP_INT_CAP) /* 0x7 */
#define UB_INT_ID (0x20 + UB_CFG1_CAP_INT_CAP) /* 0x8 */
#define  UB_FUN_EN_BIT 0
#define  UB_FUN_MASK_BIT 1
#define UB_INT_MASK (0x24 + UB_CFG1_CAP_INT_CAP) /* 0x9 */
#define  UB_INT_MASK_BIT 0x1
#define UB_INT_EN (0x28 + UB_CFG1_CAP_INT_CAP) /* 0xA */
#define  UB_INT_EN_BIT 0x1

/* UB_MEM_CAP */
#define UB_CFG1_CAP_UB_MEM 0x41800
#define UB_MEM_USI_IDX (0x4 + UB_CFG1_CAP_UB_MEM)

/* ub interrupt vector entry format */
#define UB_INTR_VECTOR_ENTRY_SIZE 0x8
#define UB_INTR_VECTOR_ID 0x0
#define UB_INTR_VECTOR_ADDR_INDEX 0x4
#define  UB_INTR_VECTOR_ADDR_INDEX_MASK GENMASK(15, 0)
#define  UB_INTR_VECTOR_MASK_MASK BIT(16)
/* ub interrupt addr entry format */
#define UB_INTR_ADDR_ENTRY_SIZE 0x20
#define UB_INTR_ADDR_ADDR_L 0x0
#define UB_INTR_ADDR_ADDR_H 0x4
#define UB_INTR_ADDR_TOKENID 0x8
#define  UB_INTR_ADDR_TOKENID_MASK GENMASK(19, 0)
#define  UB_INTR_ADDR_VALID_BIT 20
#define  UB_INTR_ADDR_VALID_MASK BIT(20)
#define UB_INTR_ADDR_DSTEID_0 0xc
#define UB_INTR_ADDR_DSTEID_1 0x10
#define UB_INTR_ADDR_DSTEID_2 0x14
#define UB_INTR_ADDR_DSTEID_3 0x18

/* PORT BASIC */
#define UB_CFG0_PORT_SLICE 0x0
#define UB_CFG0_PORT_BITMAP 0x4 /* 0x1 */
#define UB_PORT_INFO 0x24 /* 0x9 */
#define UB_PORT_TYPE 0x26 /* 0x9 */
#define  UB_PORT_TYPE_MASK BIT(0)
#define UB_NEIGHBOR_PORT_INFO 0x28 /* 0xA */
#define UB_UB_NEIGHBOR_PORT_INFO_SIZE 0x14
#define UB_PORT_NET_ADDR 0x3c /* 0xF */
#define  UB_PORT_NET_ADDR_MASK GENMASK(23, 0)
#define UB_PORT_RST 0x40 /* 0x10 */
#define  UB_PORT_RST_BIT 0x1

/* PORT CAP1 LINK */
/* Physical Port Link Status */
#define UB_PORT_PHYSICAL_PORT_LINK_STATUS (0x1c0 << 2)
#define  UB_PORT_LINK_STATE 0x1

/* PORT CAP15 QDLWS */
#define PORT_CAP15_QDLWS_CAP (0xf01 << 2)
#define PORT_CAP15_QDLWS_CTRL (0xf02 << 2)
#define PORT_CAP15_QDLWS_STATE (0xf03 << 2)
#define ASY_LINK_WIDTH_MASK BIT(0)
#define GLB_QDLWS_MASK BIT(0)
#define GLB_QDLWS_ENABLE_MASK BIT(0)
#define GLB_QDLWS_DISABLE_MASK GENMASK(31, 1)
#define TX_QDLWS_MASK BIT(1)
#define TX_QDLWS_ENABLE_MASK BIT(1)
#define TX_QDLWS_DISABLE_MASK 0xFFFFFFFD
#define RX_QDLWS_MASK BIT(2)
#define RX_QDLWS_ENABLE_MASK BIT(2)
#define RX_QDLWS_DISABLE_MASK 0xFFFFFFFB
#define TX_WIDTH_MASK GENMASK(21, 16)
#define TX_WIDTH_OFFSET 16
#define RX_WIDTH_MASK GENMASK(29, 24)
#define RX_WIDTH_OFFSET 24
#define QDLWS_EXEC_STATUS_MASK GENMASK(2, 0)
#define QDLWS_EXEC_STATUS_MAX 4

/* Error Message Queue Capability */
#define EMQ_CAP_START 0x00001400
#define UB_CAP_ERR_MSG_QUE_CTL 0x8
#define  UB_CAP_INTERRUPT_GEN_ENA 0x100

#endif /* _UAPI_UB_UBUS_UBUS_REGS_H_ */
