/* SPDX-License-Identifier: GPL-2.0+ */
/*
 * Copyright (c) 2025 HiSilicon Technologies Co., Ltd. All rights reserved.
 */

#ifndef __UB_CMDQ_H__
#define __UB_CMDQ_H__

#define UBCTL_QUERY_NL_PKT_STATS_DFX 0xA001
#define UBCTL_QUERY_NL_SSU_STATS_DFX 0xA002
#define UBCTL_QUERY_NL_ABN_DFX 0xA003

#define UBCTL_QUERY_TA_PKT_STATS_DFX 0xA006
#define UBCTL_QUERY_TA_ABN_STATS_DFX 0xA023

#define UBCTL_QUERY_DL_PKT_STATS_DFX 0xA007
#define UBCTL_QUERY_DL_LINK_STATUS_DFX 0xA008
#define UBCTL_QUERY_DL_LANE_DFX 0xA009
#define UBCTL_QUERY_DL_BIT_ERR_DFX 0xA00A
#define UBCTL_QUERY_CONF_DL_BIST_DFX 0xA020
#define UBCTL_QUERY_DL_BIST_ERR_DFX 0xA021
#define UBCTL_QUERY_DL_REPL_DFX 0xA022

#define UBCTL_NL_PKT_STATS_LEN 632
#define UBCTL_NL_SSU_STATS_LEN 408
#define UBCTL_NL_ABN_LEN 56

#define UBCTL_TA_PKT_STATS_LEN 920
#define UBCTL_TA_ABN_STATS_LEN 168

#define UBCTL_DL_PKT_STATS_LEN 984
#define UBCTL_DL_REPL_LEN 120
#define UBCTL_DL_LINK_STATUS_LEN 24
#define UBCTL_DL_LANE_LEN 24
#define UBCTL_DL_BIT_ERR_LEN 56
#define UBCTL_DL_BIST_LEN 24
#define UBCTL_DL_BIST_ERR_LEN 24

#endif
