# SPDX-License-Identifier: GPL-2.0+

cdma-$(CONFIG_UB_CDMA) := cdma_main.o cdma_dev.o cdma_chardev.o cdma_cmd.o cdma_tid.o cdma_ioctl.o \
                          cdma_api.o cdma_context.o cdma_queue.o cdma_uobj.o

obj-m += cdma.o
